#!/bin/bash

echo "🔄 Y.js WebSocket 서버 재시작 스크립트"
echo "====================================="

YJS_SERVER_IP="43.201.125.200"
YJS_PORT="1234"

echo "📋 Y.js 서버 정보:"
echo "   IP: $YJS_SERVER_IP (Elastic IP)"
echo "   포트: $YJS_PORT"
echo ""

echo "🔍 현재 실행 중인 Y.js 프로세스 확인..."
echo "다음 명령어를 Y.js 서버에서 실행하세요:"
echo ""
echo "# SSH로 Y.js 서버 접속"
echo "ssh -i your-key.pem ubuntu@$YJS_SERVER_IP"
echo ""
echo "# 현재 실행 중인 프로세스 확인"
echo "ps aux | grep yjs"
echo "netstat -tlnp | grep :$YJS_PORT"
echo ""
echo "# Y.js 서버 재시작 (PM2 사용하는 경우)"
echo "pm2 restart yjs-server"
echo "pm2 status"
echo ""
echo "# Y.js 서버 재시작 (직접 실행하는 경우)"
echo "pkill -f yjs-server"
echo "cd /path/to/yjs-server"
echo "nohup node yjs-server.js > yjs.log 2>&1 &"
echo ""
echo "# 서비스로 실행하는 경우"
echo "sudo systemctl restart yjs-server"
echo "sudo systemctl status yjs-server"
echo ""
echo "# 포트 확인"
echo "netstat -tlnp | grep :$YJS_PORT"
echo ""
echo "🌐 테스트 URL:"
echo "   WebSocket: ws://$YJS_SERVER_IP:$YJS_PORT"
echo "   Health Check: http://$YJS_SERVER_IP:$YJS_PORT/health"
echo ""
echo "📝 프론트엔드 설정 확인:"
echo "   config.js: YJS_WEBSOCKET_URL = 'ws://$YJS_SERVER_IP:$YJS_PORT'"
echo "   NoCodeEditor.jsx: wsUrl=\"ws://$YJS_SERVER_IP:$YJS_PORT\""
